### ISSUE TITLE
Not able to run sfcc-schemas in github action

### ISSUE THREAD

**Issue by swa-jaivib** [openmindlab/sfcc-schemas#19]
Hi All, Hope you’re well! 
I have a ques related to your project when I'm using it inside a github action. The workflow is about deploying meta changes to DEV instance & I’m using sfcc-schemas to validate the xmls. On my local machine, everything works great but in the github action it doesn’t.
Seems one of the file is missing & without it, the installation can proceed.

###My yml file  (Error below )###
```
name: Deploy Meta to Development 
on:
  push:
    branches:
      - main
      - develop
  pull_request:
      types: [opened, synchronize, reopened, edited]
      branches:
          - develop
          - main
          - master
          - 'feature/**'
          - 'bugfix/**'
    
jobs:
  Deploy-Meta-to-Dev:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout xyz
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: echo "$JAVA_HOME"
      
      - name: Install Node 
        uses: actions/setup-node@v4
        with: 
         node-version: 19.6.0
      
      - name: Install sfcc-schemas
        run: |
           sudo npm i -g sfcc-schemas
           sfcc-schemas-validate
      
```

###Error in the workflow:
![Screenshot 2023-12-28 at 20 35 09](https://github.com/openmindlab/sfcc-schemas/assets/121949035/c62c2b91-c7b3-423f-a9cb-37ece6ddfee8)

I’ve tried, multiple versions of node & npm but no luck! Anyone faced something similar or if you’re using sfcc-schemas in your github actions? would be good to get some insights.
Thanks  :pray:
